# Used only for simulations
TOPLEVEL = test
SRC = util/latch_d.vhdl util/ff_d.vhdl util/shift_reg.vhdl counter_large.vhdl main.vhdl test.vhdl

include ../../mk/common.build.mk
include ../../mk/$(ENV).build.mk
