# Only used on simulations 
TOPLEVEL ?= test
SRC = util/latch_d.vhdl util/ff_d.vhdl util/ff_t.vhdl util/hex.vhdl counter_8.vhdl main.vhdl test.vhdl

include ../../common.build.mk
include ../../$(ENV).build.mk
