# Used only for simulations
TOPLEVEL = test
SRC = util/latch_d.vhdl util/ff_d.vhdl util/shift_reg.vhdl counter.vhdl morse_attrs.vhdl morse_lut.vhdl  main.vhdl test.vhdl

include ../common.build.mk
include ../$(ENV).build.mk
