# Used only for simulations
TOPLEVEL = test
SRC = util/shift_reg.vhdl counter.vhdl morse_attrs.vhdl morse_lut.vhdl morse_fsm.vhdl main.vhdl test.vhdl

include ../../common.build.mk
include ../../$(ENV).build.mk
