name: Build project(s)

on: 
  push:
    tags:
      - 'v[0-9]+'

jobs:
  build-sof:
    name: Build SOF files for projects
    runs-on: ubuntu-latest
    env:
      PATH: /bin:/usr/bin:/opt/intelFPGA/quartus/bin
    steps:
      - name: Fetch Quartus Installer
        run: |
          curl -L https://github.com/CTSRD-CHERI/quartus-install/raw/513ef6a2909c4b19eded3181a1c668fce7979dd9/quartus-install.py -o quartus-install.py
          sha256sum quartus-install.py | grep -q dc8b3309ac1873706f44e76090812aad7ae1b85a007f53751f5fe41b8b8c12a7
      - name: Install Quartus
        run: |
          python ./quartus-install.py -j $(nproc) 20.1lite /opt/intelFPGA c5
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile projects
        run: |
          for i in */Makefile */*/Makefile; do
            make -C "$(dirname "$i")" ENV=quartus || exit 1
          done
      - name: Bundle build artifacts
        run: |
          git ls-tree --full-tree -r --name-only HEAD > ../repofiles
          zip -r sof.zip . -x.git -x@../repofiles
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sof.zip
